### ISSUE TITLE
package_map.jinja issue

### ISSUE THREAD

**Issue by kmkramer** [saltstack-formulas/rabbitmq-formula#44]
SL 7.3 latest Salt bootstrap install

Rendering SLS 'base:rabbitmq.install' failed: Jinja variable the template 'rabbitmq/package-map.jinja' (imported on line 1) does not export the requested name 'pkgs'

my pillar data

```
rabbitmq:
  enabled: True
  running: True
  plugin:
    rabbitmq_management:
      - enabled
  user:
    sensu:
      - password: secret
      - tags: monitoring, user
      - perms:
        - '/':
        - '.*'
        - '.*'
        - '.*'
      - runas: root
```
