### ISSUE TITLE
user password and tags always being applied even if there were no actual changes in pillar

### ISSUE THREAD

**Issue by kirill-aga** [saltstack-formulas/rabbitmq-formula#46]
I've got following section in my pillar (there is nothing else related to rabbitmq):

```
  rabbitmq:
  enabled: True
  running: True
  vhost:
    vh_name: 'rcce_vhost'
  user:
    rcce_rabbit:
      - password: '*my*secure*password*'
      - force: True
      - tags: monitoring, user
      - perms:
        - '/':
          - '.*'
          - '.*'
          - '.*'
```
state file for the minion uses the rabbitmq-formula only once, calling 'main' state. Issuing 'state.apply' command brings every time the same message as if the new user has been created, despite no actual changes in pillar:
```
          ID: rabbitmq_user_rcce_rabbit
    Function: rabbitmq_user.present
        Name: rcce_rabbit
      Result: True
     Comment: 'rcce_rabbit' was configured.
     Started: 06:48:57.213331
    Duration: 1850.237 ms
     Changes:   
              ----------
              password:
                  ----------
                  new:
                      Set password.
                  old:
              tags:
                  ----------
                  new:
                      - monitoring,
                      - user
                  old:
                      - monitoring
                      - user

```
