### ISSUE TITLE
Too many functions declared in state 'rabbitmq_user' in SLS 'rabbitmq.config'

### ISSUE THREAD

**Issue by geoffjukes** [saltstack-formulas/rabbitmq-formula#49]
Hi,

Having trouble applying the following config:

```
rabbitmq:
  version: "3.7.8"
  enabled: True
  running: True

  plugin:
    rabbitmq_management:
      - enabled

  policy:
    rabbitmq_policy:
      - name: HA
      - pattern: '.*'
      - definition: '{"ha-mode": "all"}'

  vhost:
    rpc: '/rpc'

  user:
    admin:
      - password: Secret
      - force: True
      - tags: administrator
      - perms:
        - '/rpc':
          - '.*'
          - '.*'
          - '.*'
      - runas: root

    logicmonitor:
      - password: Secret
      - force: True
      - tags: monitoring
      - perms:
        - '/rpc':
          - '.*'
          - '.*'
          - '.*'
      - runas: root

    nameko:
      - password: Secret
      - force: True
      - tags: user
      - perms:
        - '/rpc':
          - '.*'
          - '.*'
          - '.*'
      - runas: root

    config_files:
      rabbitmq.config:
        source: automation/rabbitmq.config
        context:
          heartbeat: 600
```

I'm sure I'm doing something dumb, but I'm having a hard time figuring out what. Any thoughts?
